version: "3.3"
services:

  backend-database:
    image: mongo:4
    ports:
      - "27018:27018"
    networks:
      - backend-network
    environment:
      MONGO_INITDB_DATABASE: backend-database
    command: mongod --port 27018

networks:
  backend-network:

